services:
  lobby-domain:
    build:
      context: .
      dockerfile: Dockerfile.domain
    container_name: noname-lobby-domain
    restart: unless-stopped
    ports:
      - "10.0.0.5:8081:8080"
    environment:
      - SERVER_TOKEN=$SERVER_TOKEN
